import { test, expect } from '@playwright/test'

const docsBase = '/astro-theme-aurora'
const demoBase = `${docsBase}/demo`
const route = (path: string) => `${docsBase}${path}`
const demoRoute = (path: string) => `${demoBase}${path}`

test('documentation root, Chinese page, language switch and local search work', async ({ page }) => {
  test.skip(!process.env.PLAYWRIGHT_PAGES, 'This suite targets the combined Pages artifact.')
  await page.goto(route('/'))
  await expect(page).toHaveTitle(/Aurora 3\.0/)
  await expect(page.locator('.VPHomeHero')).toContainText('Aurora 3.0')
  await expect(page.getByRole('link', { name: /Live Demo/ }).first()).toHaveAttribute('href', /\/astro-theme-aurora\/demo\//)
  await expect(page.getByRole('link', { name: 'GitHub' }).first()).toHaveAttribute('href', 'https://github.com/yanpuzhen/astro-theme-aurora')
  await page.getByRole('link', { name: /中文/ }).first().click()
  await expect(page).toHaveURL(/\/cn\//)
  await page.goto(route('/cn/'))
  await expect(page.locator('.VPHomeHero')).toContainText('使用文档')
  await expect(page.getByRole('button', { name: '指南' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: '搜索' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: '切换语言' }).first()).toBeVisible()
  await page.goto(route('/guide/getting-started'))
  await expect(page.getByRole('link', { name: /Edit this page/ })).toHaveAttribute('href', /github\.com\/yanpuzhen\/astro-theme-aurora\/edit\/dev\/docs-site\/en\/guide\/getting-started\.md/)
  await page.getByRole('button', { name: /Change language/ }).click()
  const chineseCounterpart = page.locator('a[href*="/cn/guide/getting-started.html"]:visible')
  await expect(chineseCounterpart).toHaveCount(1)
  await chineseCounterpart.click()
  await expect(page).toHaveURL(/\/astro-theme-aurora\/cn\/guide\/getting-started\.html/)
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await page.goto(route('/guide/getting-started'))
  await page.getByRole('button', { name: /Search/ }).click()
  const search = page.locator('.DocSearch-Input, input[placeholder*="Search"]')
  await expect(search).toBeVisible()
  await search.fill('Astro')
  await expect(page.locator('.search-result, .VPLocalSearchBox')).toBeVisible()
})

test('Demo nested base, Pagefind, article, lightbox, theme and mobile navigation work', async ({ page }) => {
  test.skip(!process.env.PLAYWRIGHT_PAGES, 'This suite targets the combined Pages artifact.')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(demoRoute('/'))
  await expect(page).toHaveTitle(/Aurora 3\.0/)
  await expect(page.locator('main')).toContainText('Latest articles')
  await page.goto(demoRoute('/search/'))
  const input = page.getByRole('searchbox', { name: 'Search' })
  await input.fill('Aurora')
  await expect.poll(() => page.locator('.search-result').count()).toBeGreaterThan(0)
  await expect(page.locator('.search-result').first()).toHaveAttribute('href', /\/astro-theme-aurora\/demo\//)
  await page.goto(demoRoute('/post/demo-code-showcase/'))
  await expect(page.locator('.post-html pre').first()).toBeVisible()
  await page.goto(demoRoute('/post/demo-media/'))
  await page.locator('.post-html img').first().click({ force: true })
  await expect(page.getByRole('button', { name: 'Close image' })).toBeVisible()
  await page.getByRole('button', { name: 'Close image' }).click()
  const before = await page.locator('html').getAttribute('data-theme')
  await page.getByRole('button', { name: before === 'dark' ? 'Use light theme' : 'Use dark theme' }).click()
  await expect(page.locator('html')).not.toHaveAttribute('data-theme', before || '')
  await page.goto(demoRoute('/'))
  await page.getByRole('button', { name: 'Open menu' }).click()
  await expect(page.locator('#mobile-navigation a[href="https://yanpuzhen.github.io/astro-theme-aurora/"]')).toBeVisible()
  await page.getByRole('button', { name: 'Close menu' }).click()
  await page.goto(demoRoute('/post/demo-rich-markdown/'))
  await expect(page.locator('.article-title')).toContainText('Tables, Lists')
  await page.goto(demoRoute('/'))
  await page.getByRole('button', { name: 'Open menu' }).click()
  await expect(page.locator('#mobile-navigation')).toBeVisible()
})

test('Demo pages remain readable without JavaScript', async ({ browser }) => {
  test.skip(!process.env.PLAYWRIGHT_PAGES, 'This suite targets the combined Pages artifact.')
  const noJs = await browser.newContext({ javaScriptEnabled: false })
  const page = await noJs.newPage()
  for (const path of ['/', '/cn/post/demo-markdown-fundamentals/', '/tags/', '/categories/', '/archives/']) {
    await page.goto(demoRoute(path))
    await expect(page.locator('main')).toBeVisible()
  }
  await noJs.close()
})

test('Demo Chinese locale, translated article and locale-isolated search work', async ({ page }) => {
  test.skip(!process.env.PLAYWRIGHT_PAGES, 'This suite targets the combined Pages artifact.')
  await page.goto(demoRoute('/cn/'))
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.locator('main')).toContainText('最新文章')
  await expect(page.getByRole('link', { name: /English/ }).first()).toHaveAttribute('href', /\/astro-theme-aurora\/demo\//)
  await page.goto(demoRoute('/cn/post/demo-markdown-fundamentals/'))
  await expect(page.locator('.article-title')).toContainText('Aurora Markdown')
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', /\/astro-theme-aurora\/demo\/cn\/post\/demo-markdown-fundamentals\//)
  await expect(page.locator('link[hreflang="en"]')).toHaveAttribute('href', /\/astro-theme-aurora\/demo\/post\/demo-markdown-fundamentals\//)
  await expect(page.locator('link[hreflang="zh-CN"]')).toHaveAttribute('href', /\/astro-theme-aurora\/demo\/cn\/post\/demo-markdown-fundamentals\//)
  await page.goto(demoRoute('/post/demo-markdown-fundamentals/'))
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.locator('.article-title')).toContainText('Markdown Fundamentals')
  await page.goto(demoRoute('/cn/search/'))
  const input = page.getByRole('searchbox', { name: '搜索' })
  await input.fill('Aurora')
  await expect.poll(() => page.locator('.search-result').count()).toBeGreaterThan(0)
  await expect(page.locator('.search-result').first()).toHaveAttribute('href', /\/astro-theme-aurora\/demo\/cn\//)
})

test('Demo showcase surfaces are populated, localized, layered and responsive', async ({ page }) => {
  test.skip(!process.env.PLAYWRIGHT_PAGES, 'This suite targets the combined Pages artifact.')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(demoRoute('/'))
  await expect(page.locator('#Aurora-Dia')).toBeVisible()
  await expect(page.locator('.profile-card')).toContainText('Aurora Demo')
  await expect(page.locator('.recent-comment-list')).toContainText('Mira Chen')
  await expect(page.locator('.footer-stats')).toContainText('12,480')
  await expect(page.locator('.footer-fixture-note')).toContainText('Demo showcase data')
  await expect(page.locator('.article-badge').filter({ hasText: 'Featured' }).first()).toContainText('Featured')
  await expect(page.locator('.article-badge--pinned')).toContainText('Pinned')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await page.locator('#Aurora-Dia').click()
  await expect(page.locator('#Aurora-Dia--tips-wrapper')).toHaveClass(/active/)
  await page.getByRole('link', { name: 'Open search' }).click()
  await expect(page.locator('.search-modal')).toBeVisible()
  const searchLayering = await page.locator('.search-modal').evaluate((element) => Number.parseInt(getComputedStyle(element).zIndex, 10))
  const diaLayering = await page.locator('#bot-container').evaluate((element) => Number.parseInt(getComputedStyle(element).zIndex, 10))
  expect(searchLayering).toBeGreaterThan(diaLayering)
  await page.keyboard.press('Escape')

  await page.goto(demoRoute('/links/'))
  await expect(page.locator('.link-card')).toHaveCount(7)
  await expect(page.locator('.link-group')).toHaveCount(2)
  await page.goto(demoRoute('/cn/links/'))
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.locator('.link-card')).toHaveCount(7)

  await page.goto(demoRoute('/post/demo-math/'))
  await expect(page.locator('.katex')).toHaveCount(9)
  await expect(page.locator('.katex-display')).toHaveCount(5)
  await expect(page.locator('.katex-mathml')).toHaveCount(9)
  await expect(page.locator('.katex-mathml').first()).toHaveCSS('clip-path', 'inset(50%)')
  await expect(page.locator('.post-html')).toContainText('MatrixFormula')

  await page.goto(demoRoute('/post/demo-media/'))
  await page.locator('.post-html img').first().click({ force: true })
  await expect(page.locator('.lightbox-dialog')).toBeVisible()
  const lightboxLayering = await page.locator('.lightbox-dialog').evaluate((element) => Number.parseInt(getComputedStyle(element).zIndex, 10))
  expect(lightboxLayering).toBeGreaterThan(diaLayering)

  await page.goto(demoRoute('/page/2/'))
  await expect(page.locator('main')).toContainText('Latest articles')
  await page.goto(demoRoute('/archives/2/'))
  await expect(page.locator('main')).toContainText('Archives')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(demoRoute('/'))
  await expect(page.locator('#Aurora-Dia')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.goto(demoRoute('/cn/post/demo-math/'))
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.locator('.katex')).toHaveCount(9)

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(demoRoute('/'))
  await expect(page.locator('#Aurora-Dia')).toBeVisible()
  const diaAnimations = await page.locator('#Aurora-Dia, #Aurora-Dia--eyes .Aurora-Dia--eye, .Aurora-Dia--platform, #Aurora-Dia--tips-wrapper').evaluateAll((elements) => elements.map((element) => getComputedStyle(element).animationName))
  expect(diaAnimations.every((animation) => animation === 'none')).toBeTruthy()
})
