import { readFileSync } from 'node:fs'
import { strict as assert } from 'node:assert'
import { createHash } from 'node:crypto'
import { legacyUid } from '../src/lib/legacy-identity.ts'
import { normalizeLegacyData, slugify } from '../src/lib/content.ts'
import { commentIdentity, commentIdentityAliases, normalizeCommentPath } from '../src/lib/comments.ts'
import { assertNoRouteCollisions } from '../src/lib/routing.ts'
import { paginate } from '../src/lib/posts.ts'

const fixture = JSON.parse(readFileSync(new URL('../tests/fixtures/legacy-title-hash.json', import.meta.url), 'utf8'))
for (const item of fixture) {
  const reference = createHash('md5').update(`post_uid___${item.title}`).digest('hex')
  assert.equal(reference, item.postUid, `fixture was not generated by the audited legacy algorithm: ${JSON.stringify(item.title)}`)
  assert.equal(legacyUid(item.title), item.postUid, `post UID drift: ${JSON.stringify(item.title)}`)
  assert.equal(normalizeLegacyData({ title: item.title, date: '2026-01-01' }).legacyUid, item.postUid)
}
assert.equal(legacyUid('Hello World', 'page'), createHash('md5').update('page_uid___Hello World').digest('hex'))
assert.notEqual(legacyUid('café'), legacyUid('café'), 'NFC and NFD titles must remain distinct')
assert.notEqual(slugify('C++'), slugify('C#'), 'punctuation-heavy taxonomy values must not collapse to one route')
assert.deepEqual(paginate(['a', 'b', 'c'], 2, 2), { items: ['c'], page: 2, pageSize: 2, pageCount: 2, total: 3 })
assert.deepEqual(paginate([], 0, 0), { items: [], page: 1, pageSize: 1, pageCount: 1, total: 0 })

const input = { legacyUid: 'legacy-uid', canonicalPath: '/aurora/post/new/', legacyPath: 'https://example.com/post/old/?x=1' }
assert.equal(normalizeCommentPath(input.legacyPath), '/post/old/')
assert.equal(normalizeCommentPath(input.legacyPath, false), '/post/old')
assert.equal(commentIdentity('gitalk', input), 'legacy-uid')
assert.equal(commentIdentity('gitalk', { ...input, providerId: 'pathname' }), '/post/old/')
assert.equal(commentIdentity('valine', input), '/post/old')
assert.equal(commentIdentity('twikoo', input), '/post/old/')
assert.equal(commentIdentity('waline', input), '/post/old/')
assert.deepEqual(commentIdentityAliases('gitalk', input), ['legacy-uid', '/post/old/', '/aurora/post/new/'])
assert.deepEqual(commentIdentityAliases('valine', input), ['/post/old', '/post/old/', '/aurora/post/new/', 'legacy-uid'])

const routePost = (id, overrides = {}) => ({ id, data: {
  title: id, slug: id, permalink: undefined, permalinkMode: 'slug', legacyUid: `${id}-uid`,
  legacyPermalinks: [], ...overrides,
} })
assert.throws(() => assertNoRouteCollisions([routePost('same'), routePost('same-other', { slug: 'same' })]), /Route collision/)
assert.throws(() => assertNoRouteCollisions([routePost('one', { legacyUid: 'same-uid' }), routePost('two', { legacyUid: 'same-uid' })]), /Route collision/)
assert.throws(() => assertNoRouteCollisions([routePost('one', { permalink: '/shared/' }), routePost('two', { permalink: '/shared/' })]), /Route collision/)
assert.throws(() => assertNoRouteCollisions([routePost('one', { legacyPermalinks: ['/post/two/'] }), routePost('two')]), /Route collision/)
assert.throws(() => assertNoRouteCollisions([routePost('one', { permalink: '/tags/one/' })]), /reserved site route/)
assert.throws(() => assertNoRouteCollisions([routePost('one', { permalink: '/categories/one/' })]), /reserved site route/)

console.log(`Verified ${fixture.length} legacy title-hash cases and provider identity modes`)
